services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    command: sh -c "npm install && npm run dev"
    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_key_somente_para_lab_123!
